In [3]:
import seaborn as sns
import pandas as pd
import plotly.express as px
import numpy as np
from sklearn import linear_model

In [4]:
data = sns.load_dataset("tips")
data.head(5)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [8]:
features = data[["total_bill"]]
tip = data["tip"]

from sklearn import linear_model
f = linear_model.LinearRegression(fit_intercept = False)
f.fit(features, tip)

LinearRegression(fit_intercept=False)

In [5]:
# fit a model on total_bill and size
two_features = data[["total_bill", "size"]]
tip = data["tip"]

f2 = linear_model.LinearRegression(fit_intercept = False)
f2.fit(two_features, tip)

LinearRegression(fit_intercept=False)

In [6]:
#show coefficients
f2.coef_

array([0.1007119 , 0.36209717])

In [7]:
# make a prediction for a table with $10 total bill and 3 people seated
f2.predict([[10, 3]])

/home/vinny/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([2.09341054])

In [9]:
data["prediction"] = f.predict(data[["total_bill"]])

In [10]:
data["prediction_2d"] = f2.predict(data[["total_bill", "size"]])
data.head(5)

total_bill   tip     sex smoker  day    time  size  prediction  \
0       16.99  1.01  Female     No  Sun  Dinner     2    2.442005   
1       10.34  1.66    Male     No  Sun  Dinner     3    1.486188   
2       21.01  3.50    Male     No  Sun  Dinner     3    3.019807   
3       23.68  3.31    Male     No  Sun  Dinner     2    3.403571   
4       24.59  3.61  Female     No  Sun  Dinner     4    3.534367   

   prediction_2d  
0       2.435290  
1       2.127653  
2       3.202249  
3       3.109052  
4       3.924894

In [11]:
data

total_bill   tip     sex smoker   day    time  size  prediction  \
0         16.99  1.01  Female     No   Sun  Dinner     2    2.442005   
1         10.34  1.66    Male     No   Sun  Dinner     3    1.486188   
2         21.01  3.50    Male     No   Sun  Dinner     3    3.019807   
3         23.68  3.31    Male     No   Sun  Dinner     2    3.403571   
4         24.59  3.61  Female     No   Sun  Dinner     4    3.534367   
..          ...   ...     ...    ...   ...     ...   ...         ...   
239       29.03  5.92    Male     No   Sat  Dinner     3    4.172537   
240       27.18  2.00  Female    Yes   Sat  Dinner     2    3.906633   
241       22.67  2.00    Male    Yes   Sat  Dinner     2    3.258402   
242       17.82  1.75    Male     No   Sat  Dinner     2    2.561302   
243       18.78  3.00  Female     No  Thur  Dinner     2    2.699285   

     prediction_2d  
0         2.435290  
1         2.127653  
2         3.202249  
3         3.109052  
4         3.924894  
..             ...  
239       4.009958  
240       3.461544  
241       3.007333  
242       2.518880  
243       2.615564  

[244 rows x 9 columns]

In [12]:
from sklearn.metrics import mean_squared_error
mean_squared_error(data["prediction"], data["tip"])

1.178116115451317

In [13]:
mean_squared_error(data["prediction_2d"], data["tip"])

1.06482122862577

In [14]:
px.scatter_3d(data, x = "total_bill", y = "size", z = "tip")

In [16]:
# This code is not something we expect you to understand!
# It's just computing predictions for various bills and table sizes
table_bills, table_sizes = np.meshgrid(range(50), range(6))
tip_predictions = ( 0.1007119 * table_bills + 0.3621 * table_sizes)

In [17]:
import plotly.graph_objects as go

fig = go.Figure()
fig.add_trace(go.Scatter3d(x = data["total_bill"], y = data["size"], z = data["tip"],
                         mode = "markers", name = "actual"))
fig.add_trace(go.Surface(x = table_bills, y = table_sizes, z = tip_predictions, name = "predicted"))
fig.show()

In [18]:
f.coef_

array([0.1437319])

In [19]:
f2.coef_

array([0.1007119 , 0.36209717])